const ML_SERVICE_URL = process.env.ML_SERVICE_URL || 'http://127.0.0.1:8000';

const MEDICAL_DISCLAIMER =
  'EDUCATIONAL DEMONSTRATION ONLY: This risk score is generated by an artificial intelligence model ' +
  'for educational/project demonstration purposes and MUST NOT be used as a clinical diagnosis or medical advice. ' +
  'Always consult a qualified healthcare professional for medical diagnostic evaluation.';

/**
 * Built-in Clinical Risk Assessment Engine (used as high-availability fallback
 * when the Python FastAPI microservice is offline or unreachable, e.g. on serverless Vercel).
 */
const calculateClinicalFallbackRisk = (payload) => {
  const { glucose, bmi, age, blood_pressure, insulin } = payload;

  let score = 5;
  const high_factors = [];

  if (glucose >= 200) {
    score += 45;
    high_factors.push('Severely Elevated Glucose (>= 200 mg/dL)');
  } else if (glucose >= 140) {
    score += 35;
    high_factors.push('Elevated Glucose (>= 140 mg/dL)');
  } else if (glucose >= 100) {
    score += 15;
    high_factors.push('Pre-diabetic Fasting Glucose (100-139 mg/dL)');
  }

  if (bmi >= 35) {
    score += 25;
    high_factors.push('Obese Class II BMI (>= 35.0)');
  } else if (bmi >= 30) {
    score += 20;
    high_factors.push('Elevated BMI (>= 30.0)');
  } else if (bmi >= 25) {
    score += 10;
  }

  if (age >= 50) {
    score += 15;
    high_factors.push('Age Category (>= 50 years)');
  } else if (age >= 40) {
    score += 10;
    high_factors.push('Age Category (>= 40 years)');
  }

  if (blood_pressure >= 90) {
    score += 10;
    high_factors.push('Elevated Diastolic BP (>= 90 mm Hg)');
  }

  if (insulin >= 160) {
    score += 10;
    high_factors.push('Elevated 2-hr Insulin (>= 160 mu U/ml)');
  }

  const rawProbability = Math.min(Math.max(score / 100, 0.05), 0.95);
  const risk_probability = Math.round(rawProbability * 1000) / 1000;
  const risk_percentage = Math.round(risk_probability * 1000) / 10;

  let risk_level = 'Low Risk';
  let prediction = 0;
  if (risk_probability >= 0.65) {
    risk_level = 'High Risk';
    prediction = 1;
  } else if (risk_probability >= 0.35) {
    risk_level = 'Moderate Risk';
    prediction = 0;
  }

  return {
    prediction,
    risk_probability,
    risk_percentage,
    risk_level,
    key_contributing_factors: high_factors,
    model_used: 'Clinical Risk Assessment Engine (Random Forest Emulation)',
    disclaimer: MEDICAL_DISCLAIMER,
  };
};

/**
 * Communicates with the Python FastAPI Machine Learning Service
 * to calculate Diabetes Risk using the trained Random Forest Classifier.
 * Falls back to built-in Clinical Risk Assessment Engine if service is unreachable.
 *
 * @param {Object} metrics - Clinical biometric parameters
 * @returns {Promise<Object>} ML prediction result JSON
 */
const predictDiabetesRisk = async (metrics) => {
  const payload = {
    pregnancies: Number(metrics.pregnancies) || 0,
    glucose: Number(metrics.glucose) || 120.0,
    blood_pressure: Number(metrics.bloodPressure || metrics.blood_pressure) || 70.0,
    skin_thickness: Number(metrics.skinThickness || metrics.skin_thickness) || 20.0,
    insulin: Number(metrics.insulin) || 79.0,
    bmi: Number(metrics.bmi) || 25.0,
    diabetes_pedigree_function: Number(metrics.diabetesPedigreeFunction || metrics.diabetes_pedigree_function) || 0.47,
    age: Number(metrics.age) || 30,
  };

  const endpoint = `${ML_SERVICE_URL}/predict/diabetes`;

  try {
    const controller = new AbortController();
    const timeoutId = setTimeout(() => controller.abort(), 3000);

    const response = await fetch(endpoint, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(payload),
      signal: controller.signal,
    });

    clearTimeout(timeoutId);

    if (!response.ok) {
      console.warn(`[!] ML Service returned ${response.status}, using clinical fallback.`);
      return calculateClinicalFallbackRisk(payload);
    }

    const data = await response.json();
    return data;
  } catch (error) {
    console.warn(`[i] ML Microservice not reachable at ${ML_SERVICE_URL}. Using built-in Clinical Risk Assessment fallback.`);
    return calculateClinicalFallbackRisk(payload);
  }
};

module.exports = {
  predictDiabetesRisk,
};
