"""
Stand-alone Diabetes Risk Prediction Engine.

Loads saved Scikit-Learn Joblib pipeline and executes prediction on a single patient's biometric inputs.
"""

import os
import joblib
import pandas as pd
import numpy as np

MEDICAL_DISCLAIMER = (
    "EDUCATIONAL DEMONSTRATION ONLY: This risk score is generated by an artificial intelligence model "
    "for educational/project demonstration purposes and MUST NOT be used as a clinical diagnosis or medical advice. "
    "Always consult a qualified healthcare professional for medical diagnostic evaluation."
)

ALL_FEATURE_COLUMNS = [
    'Pregnancies', 'Glucose', 'BloodPressure',
    'SkinThickness', 'Insulin', 'BMI',
    'DiabetesPedigreeFunction', 'Age'
]


class DiabetesPredictor:
    def __init__(self, model_path: str = None):
        if model_path is None:
            base_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
            model_path = os.path.join(base_dir, 'models', 'diabetes_model.joblib')

        if not os.path.exists(model_path):
            raise FileNotFoundError(
                f"Model file not found at {model_path}. Please run 'python ml/src/train.py' first."
            )

        self.model_pipeline = joblib.load(model_path)

    def predict(self, patient_data: dict) -> dict:
        """
        Executes prediction for a single patient dictionary.
        Required keys: Pregnancies, Glucose, BloodPressure, SkinThickness, Insulin, BMI, DiabetesPedigreeFunction, Age
        """
        # Convert dictionary to DataFrame with required column sequence
        input_df = pd.DataFrame([{
            'Pregnancies': float(patient_data.get('Pregnancies', 0)),
            'Glucose': float(patient_data.get('Glucose', 0)),
            'BloodPressure': float(patient_data.get('BloodPressure', 0)),
            'SkinThickness': float(patient_data.get('SkinThickness', 0)),
            'Insulin': float(patient_data.get('Insulin', 0)),
            'BMI': float(patient_data.get('BMI', 0)),
            'DiabetesPedigreeFunction': float(patient_data.get('DiabetesPedigreeFunction', 0.1)),
            'Age': float(patient_data.get('Age', 25))
        }])

        # Predict probability & class using serialized pipeline
        prediction = int(self.model_pipeline.predict(input_df)[0])
        probabilities = self.model_pipeline.predict_proba(input_df)[0]
        risk_probability = float(np.round(probabilities[1], 4))

        # Determine Risk Level Category
        if risk_probability < 0.35:
            risk_level = "Low Risk"
        elif risk_probability < 0.65:
            risk_level = "Moderate Risk"
        else:
            risk_level = "High Risk"

        # Key Factor Analysis
        high_factors = []
        if patient_data.get('Glucose', 0) >= 140:
            high_factors.append("Elevated Glucose (>= 140 mg/dL)")
        if patient_data.get('BMI', 0) >= 30:
            high_factors.append("Elevated BMI (>= 30.0)")
        if patient_data.get('Age', 0) >= 45:
            high_factors.append("Age Category (>= 45 years)")

        return {
            "prediction": prediction,
            "risk_probability": risk_probability,
            "risk_percentage": round(risk_probability * 100, 1),
            "risk_level": risk_level,
            "key_contributing_factors": high_factors,
            "model_used": "RandomForestClassifier (Pima Indians Dataset)",
            "disclaimer": MEDICAL_DISCLAIMER
        }


# Global singleton instance for quick API import
_predictor_instance = None


def get_predictor() -> DiabetesPredictor:
    global _predictor_instance
    if _predictor_instance is None:
        _predictor_instance = DiabetesPredictor()
    return _predictor_instance
